#!/bin/bash -xe

# builds both device and simulator builds

DBG_SYMS=OFF
CM_OPTS="-DGDJ_INSTALL_DEBUG_SYMBOLS=$DBG_SYMS -DGDJ_DOUBLE_PRECISION=FALSE"

# mac editor 
cmake --preset macos-clang $CM_OPTS && cmake --build --preset macos-clang-editor-distribution --target install

# visionOS simulator
cmake --preset macos-visionos-simulator $CM_OPTS && cmake --build --preset macos-visionos-simulator-distribution --target install

# visionOS device
cmake --preset macos-visionos $CM_OPTS && cmake --build --preset macos-visionos-distribution --target install
